version: '2.1'

jobs:
    composer:
        docker:
            - image: composer
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                composer install --ignore-platform-reqs --no-interaction;
            - save_cache:
                  key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
                  paths:
                      - ./vendor
            - persist_to_workspace:
                  root: .
                  paths:
                      - vendor

    phpcs:
        docker:
            - image: steevanb/php-code-sniffs:3.0.1
        working_directory: /var/repository
        steps:
            - checkout
            - run:
                  name: phpcs
                  command: bin/phpcs

    phpcf:
        docker:
            - image: steevanb/php-code-fixer:2.0.23
        working_directory: /var/repository
        steps:
            - checkout
            - run:
                  name: phpcf
                  command: bin/phpcf

    composerRequireChecker:
        docker:
            - image: steevanb/composer-require-checker:2.1.0
        working_directory: /app
        steps:
            - checkout
            - restore_cache:
                key: vendor-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}
            - run:
                name: composer-require-checker
                command: composer-require-checker

workflows:
    version: '2.1'
    CI:
        jobs:
            - phpcs
            - phpcf
            - composer
            - composerRequireChecker:
                requires:
                    - composer
